/**
 * SMART - State Machine ARchiTecture
 *
 * Copyright (C) 2012 Individual contributors as indicated by
 * the @authors tag
 *
 * This file is a part of SMART.
 *
 * SMART is a free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * SMART is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 *
 *
 * */
 
/**
 * ************************************************************
 * HEADERS
 * ************************************************************
 * File:                org.anon.smart.workbench.data.Alarm
 * Author:              rsankarx
 * Revision:            1.0
 * Date:                28-11-2016
 *
 * ************************************************************
 * REVISIONS
 * ************************************************************
 * An alarm raised on a workspace object
 *
 * ************************************************************
 * */

package org.anon.smart.workbench.data;

import java.util.UUID;

public class Alarm implements java.io.Serializable
{
    private String alarmId;
    private String objectId; //the internal id generated by smart
    private int code;
    private String name;
    private String assignedTo;
    private String resolveMessage;

    public Alarm(UUID id, int cde, String nm)
    {
        alarmId = UUID.randomUUID().toString();
        objectId = id.toString();
        code = cde;
        name = nm;
    }

    public void assignTo(String user)
    {
        assignedTo = user;
    }

    public void resolveAlarm(String msg)
    {
        resolveMessage = msg;
    }
}

